# Generated by the SOULs protocol buffer compiler.  DO NOT EDIT!
# Source: blog.proto for package 'Souls'

require "./app/services/blog_pb"
module Souls
  module Blog
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'Souls.Blog'

      rpc :GetArticle, ::Souls::GetArticlRequest, ::Souls::GetArticleReply
      # Demonstrates a server streamer call
      rpc :GetArticles, ::Souls::GetArticlesRequest, stream(::Souls::Article)
      # Demonstrates a client streaming call
      rpc :CreateArticle, ::Souls::Article, ::Souls::CreateArticleReply
      rpc :UpdateArticles, stream(::Souls::Article), ::Souls::UpdateArticlesReply
      rpc :DeleteArticle, ::Souls::DeleteArticlRequest, ::Souls::DeleteArticleReply
      # Demonstrates a bidirectional streaming call
      rpc :CreateArticlesInStream, stream(::Souls::Article), stream(::Souls::Article)
      rpc :SayHello, ::Souls::HelloRequest, ::Souls::HelloReply
      rpc :SayHelloAgain, ::Souls::HelloRequest, ::Souls::HelloReply
    end

    Stub = Service.rpc_stub_class
  end
end
