steps:
- name: gcr.io/cloud-builders/docker
  args:
  - image
  - build
  - -t
  - asia.gcr.io/$PROJECT_ID/graphql-api
  - .

- name: gcr.io/cloud-builders/docker
  args:
  - image
  - push
  - asia.gcr.io/$PROJECT_ID/graphql-api

- name: gcr.io/cloud-builders/gcloud
  args:
  - run
  - deploy
  - graphql-api
  - --image=asia.gcr.io/$PROJECT_ID/graphql-api
  - --platform=managed
  - --region=asia-northeast1
  - --allow-unauthenticated
  - --memory=2048Mi
  - --concurrency=80
  - --port=8080
  - --service-account=elsoul-main@$PROJECT_ID.iam.gserviceaccount.com
  - --set-cloudsql-instances=elsoul2:asia-northeast1:elsoul

timeout: 1600s
options:
  machineType: N1_HIGHCPU_8
