apiVersion: v1
kind: Secret
metadata:
  name: graphql-api-secret
type: Opaque
data:
  db_pw: xxxxxxxx
  db_user: xxxxxxx
  db_host: xxxxxxx
  secret_key_base: xxxxxxxxxxxxxxxxxxxxx
  project_id: xxxxxxx
  google_application_credentials: xxxxxxxxxxxxxxxxx
  grpc_server_url: xxxxxxxxxxxxxxxxxxx