apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elquest-api
  name: elquest-api
spec:
  selector:
    matchLabels:
      app: elquest-api
  replicas: 3
  template:
    metadata:
      labels:
        app: elquest-api
    spec:
      containers:
      - name: elquest-api
        image: asia.gcr.io/el-quest/elquest-api:v1
        ports:
          - containerPort: 3000
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 2000Mi
          requests:
            cpu: 300m
            memory: 1500Mi