apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elquest-api-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: elquest-api-ip
    ingress.gcp.kubernetes.io/pre-shared-cert: elquest-api-ssl
spec:
  rules:
  - host: elquest-api.el-soul.com
    http:
      paths:
      - backend:
          serviceName: elquest-api-service
          servicePort: 80
