kind: Service
apiVersion: v1
metadata:
  name: elquest-api-service
spec:
  selector:
    app: elquest-api
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
