default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: souls_api_dev

production:
  <<: *default
  database: souls_api_production
  username: <%= ENV.fetch("DB_USER") { "" } %>
  password: <%= ENV.fetch("DB_PW") { "" } %>
  host: <%= ENV.fetch("DB_HOST") { "" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  <<: *default
  database: souls_api_test
